[0m06:43:40.707260 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E9DD5AB350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E9DD5FF5D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E9DD5AA8D0>]}


============================== 06:43:40.723121 | ae08640c-3b73-48cf-a9e4-6724cde64d01 ==============================
[0m06:43:40.723121 [info ] [MainThread]: Running with dbt=1.10.13
[0m06:43:40.723121 [debug] [MainThread]: running dbt with arguments {'write_json': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\RAU45\\.dbt', 'no_print': 'None', 'use_colors': 'True', 'warn_error': 'None', 'static_parser': 'True', 'partial_parse': 'True', 'log_path': 'logs', 'send_anonymous_usage_stats': 'True', 'fail_fast': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'indirect_selection': 'eager', 'version_check': 'True', 'use_experimental_parser': 'False', 'quiet': 'False', 'introspect': 'True', 'empty': 'False', 'log_cache_events': 'False', 'debug': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --select plans.sql', 'printer_width': '80', 'target_path': 'None'}
[0m06:43:40.723121 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\OneDrive - Rudder Analytics Pvt Ltd\Learning\@Data Engineering\DBT\Zorro_dbt_test\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m06:43:40.723121 [debug] [MainThread]: Command `dbt run` failed at 06:43:40.723121 after 0.08 seconds
[0m06:43:40.723121 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E9DD5AA7D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E9D6869B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E9DD5937D0>]}
[0m06:43:40.723121 [debug] [MainThread]: Flushing usage events
[0m06:43:41.963763 [debug] [MainThread]: An error was encountered while trying to flush usage events
